# Generated by Django 5.2.3 on 2025-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=10),
        ),
    ]
